import React, { useState } from 'react'
import Navbar from '../../components/Navbar'
import Footer from '../../components/Footer';
import { useFlags, useFlagsmith } from 'flagsmith/react';
import Maintainance from '../Maintainance';
const AboutPage = () => {
    const flags = useFlags(['maintenance','dark_mode']); // only causes re-render if specified flag values / traits change

    const maintain = flags.maintenance.enabled;
    
    const dark = flags.dark_mode.enabled;

    return (
        <>
            {maintain == true ? <Maintainance/> :
                <div className={dark?"bg-black text-white min-h-screen":"bg-gray-200 min-h-screen"}>
                    <div className={dark?'bg-black text-white':'bg-white'}>
                    <Navbar darkMode={dark}/>
                    </div>
                    <div className="container mx-auto px-4 py-8 grid">
                        <h1 className="text-3xl font-semibold text-center mb-6">About DIY-IT</h1>
                        <div className='grid grid-cols-5 gap-10'>
                            <div className='col-span-3 flex items-center flex-col py-14'>
                                <p className={dark?"text-lg text-gray-200 mb-8":"text-lg text-gray-800 mb-8"}>
                                    DIY-IT is a web app  designed to provide users with step-by-step guides for creating various crafts using household items. Whether you're a beginner looking to explore the world of crafting or an experienced crafter seeking new projects, our platform offers a diverse range of DIY ideas to suit your interests and skill level.
                                </p>
                                <p className={dark?"text-lg text-gray-200 mb-8":"text-lg text-gray-800 mb-8"}>
                                    In addition to curated DIY projects, this platform features an AI-powered custom DIY product generator. This innovative tool allows users to input their preferences and receive personalized crafting ideas generated by our AI algorithm. It's a fun and creative way to explore new crafting possibilities and make the most out of your free time.
                                </p>
                                <p className={dark?"text-lg text-gray-200 mb-8":"text-lg text-gray-800 mb-8"}>
                                    Whether you're looking to spruce up your living space, create unique gifts for loved ones, or simply unwind with a creative activity, our web app is here to inspire and empower you on your crafting journey. Use DIY-IT today and unleash your creativity with DIY Crafts!
                                </p>
                            </div>
                            <div className='col-span-2 h-[38rem] relative'>
                                <img src="https://images.unsplash.com/photo-1608613304899-ea8098577e38?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" className='absolute inset-0 w-full h-full object-cover' alt="DIY Crafts" />
                            </div>
                        </div>

                    </div>
                    <Footer darkMode={dark}/>
                </div>
            }
        </>
    );
}

export default AboutPage;
